using UnityEngine;

namespace HttpSiraStatus.Interfaces
{
#pragma warning disable IDE1006 // 命名スタイル
    public interface IGameStatus
    {
        bool advancedHUD { get; }
        float afterSwingRating { get; }
        bool autoRestart { get; }
        int batteryEnergy { get; }
        int batteryLives { get; }
        int beatmapEventType { get; }
        int beatmapEventValue { get; }
        float beforSwingRating { get; }
        int bombsCount { get; }
        string characteristic { get; }
        Color? colorEnvironment0 { get; }
        Color? colorEnvironment1 { get; }
        Color? colorEnvironmentBoost0 { get; }
        Color? colorEnvironmentBoost1 { get; }
        Color? colorObstacle { get; }
        Color? colorSaberA { get; }
        Color? colorSaberB { get; }
        int combo { get; }
        int currentMaxScore { get; }
        int currentSongTime { get; }
        float cutDirectionDeviation { get; }
        int cutDistanceScore { get; }
        float cutDistanceToCenter { get; }
        int cutMultiplier { get; }
        float cutNormalX { get; }
        float cutNormalY { get; }
        float cutNormalZ { get; }
        float cutPointX { get; }
        float cutPointY { get; }
        float cutPointZ { get; }
        string difficulty { get; }
        string difficultyEnum { get; }
        bool directionOK { get; }
        float energy { get; }
        string environmentEffects { get; }
        string environmentName { get; }
        int finalScore { get; }
        string gameplayType { get; }
        bool hideNoteSpawningEffect { get; }
        int hitBombs { get; }
        int hitNotes { get; }
        int initialScore { get; }
        int lastNoteScore { get; }
        bool leftHanded { get; }
        long length { get; }
        string levelAuthorName { get; }
        string levelId { get; }
        int maxCombo { get; }
        string maxRank { get; }
        int maxScore { get; }
        int missedNotes { get; }
        bool modBatteryEnergy { get; }
        bool modDisappearingArrows { get; }
        string mode { get; }
        bool modFailOnSaberClash { get; }
        bool modFastNotes { get; }
        bool modGhostNotes { get; }
        float modifierMultiplier { get; }
        bool modInstaFail { get; }
        bool modNoArrows { get; }
        bool modNoBombs { get; }
        bool modNoFail { get; }
        string modObstacles { get; }
        bool modProMode { get; }
        bool modSmallNotes { get; }
        string modSongSpeed { get; }
        bool modStrictAngles { get; }
        bool modZenMode { get; }
        bool multiplayer { get; }
        int multiplier { get; }
        float multiplierProgress { get; }
        bool noHUD { get; }
        string noteCutDirection { get; }
        int noteID { get; }
        float noteJumpSpeed { get; }
        float noteJumpStartBeatOffset { get; }
        int noteLayer { get; }
        int noteLine { get; }
        int notesCount { get; }
        string noteType { get; }
        int obstaclesCount { get; }
        bool partyMode { get; }
        int passedBombs { get; }
        int passedNotes { get; }
        long paused { get; }
        float playerHeight { get; }
        string rank { get; }
        int rawScore { get; }
        bool reduceDebris { get; }
        float relativeScore { get; }
        float saberDirX { get; }
        float saberDirY { get; }
        float saberDirZ { get; }
        float saberSpeed { get; }
        float saberTrailIntensity { get; }
        string saberType { get; }
        bool saberTypeOK { get; }
        string scene { get; }
        int score { get; }
        float sfxVolume { get; }
        string sliderHeadCutDirection { get; }
        int sliderHeadLayer { get; }
        int sliderHeadLine { get; }
        string sliderTailCutDirection { get; }
        int sliderTailLayer { get; }
        int sliderTailLine { get; }
        bool softFailed { get; }
        string songAuthorName { get; }
        float songBPM { get; }
        string songCover { get; }
        string songHash { get; }
        string songName { get; }
        float songSpeedMultiplier { get; }
        string songSubName { get; }
        long songTimeOffset { get; }
        bool speedOK { get; }
        long start { get; }
        bool staticLights { get; }
        float swingRating { get; }
        float timeDeviation { get; }
        float timeToNextBasicNote { get; }
        string updateCause { get; }
        bool wasCutTooSoon { get; }
    }
}